### ISSUE TITLE
Search engine doesn't correctly manage some additional spaces

### ISSUE THREAD

**Issue by dzc34** [etalab/sill.etalab.gouv.fr#28]
Search engine doesn't correctly manage some additional spaces : 
- double space 
- space before 
- space after

Following examples work correctly :
- `Pycharm` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm&year=2020
- `Pycharm ` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm+&year=2020
- `Pycharm CE` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm+CE&year=2020

Following examples do not work:
- ` Pycharm` ---> https://sill.etalab.gouv.fr/fr/software?q=+Pycharm&year=2020
- `Pycharm  ` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm++&year=2020
- `Pycharm CE ` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm+CE+&year=2020
- `Pycharm   CE` ---> https://sill.etalab.gouv.fr/fr/software?q=Pycharm+++CE&year=2020

**Comment by bzg** [comment]
Fixed in production, thanks a lot!
